services:
  db:
    image: postgres:16.8-alpine3.20
    container_name: db
    restart: unless-stopped
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    volumes:
      - postgres-controle-armarios:/var/lib/postgresql/data
    networks:
      - controle_armarios_net

  app:
    image: natanbarboza1408/controle-de-armarios:latest
    container_name: app
    restart: unless-stopped
    ports:
      - "80:8000"
    volumes:
      - app-logs:/app/logs
    networks:
      - controle_armarios_net
    depends_on:
      - db

volumes:
  postgres-controle-armarios:
  app-logs:

networks:
  controle_armarios_net:
    driver: bridge