# Generated by Django 5.1.7 on 2025-03-28 23:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinets', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cabinets',
            name='final_datetime',
        ),
        migrations.RemoveField(
            model_name='cabinets',
            name='initial_datetime',
        ),
        migrations.RemoveField(
            model_name='cabinets',
            name='owner',
        ),
        migrations.CreateModel(
            name='CabinetsManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_datetime', models.DateTimeField(auto_now_add=True)),
                ('final_datetime', models.DateTimeField(auto_now=True)),
                ('cabinet_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cabinets.cabinets')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.users')),
            ],
        ),
    ]
