# Generated by Django 5.1.7 on 2025-03-28 23:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinets', '0003_alter_cabinetsmanager_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabinetsmanager',
            name='cabinet_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cabinets.cabinets', unique=True),
        ),
    ]
