# Generated by Django 5.1.7 on 2025-03-31 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinets', '0004_alter_cabinetsmanager_cabinet_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabinets',
            name='reserved',
            field=models.BooleanField(default=False),
        ),
    ]
