# Generated by Django 5.1.7 on 2025-03-31 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinets', '0005_cabinets_reserved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabinets',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
