# Generated by Django 5.1.7 on 2025-03-31 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinets', '0006_alter_cabinets_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabinetsmanager',
            name='cabinet_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cabinets.cabinets'),
        ),
    ]
