# Generated by Django 5.1.7 on 2025-03-31 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinets', '0007_alter_cabinetsmanager_cabinet_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabinetsmanager',
            name='final_datetime',
            field=models.DateTimeField(blank=True),
        ),
    ]
