# Generated by Django 5.1.7 on 2025-04-01 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cabinets', '0008_alter_cabinetsmanager_final_datetime'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CabinetsManager',
        ),
    ]
