# Generated by Django 5.1.7 on 2025-03-28 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('enterprise_id', models.CharField(max_length=10)),
                ('status', models.BooleanField()),
                ('personal_id', models.CharField(max_length=14)),
            ],
        ),
    ]
