# Generated by Django 5.1.7 on 2025-03-31 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='enterprise_id',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='personal_id',
            field=models.CharField(max_length=14, unique=True),
        ),
    ]
