# Generated by Django 5.1.7 on 2025-04-01 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cabinets', '0009_delete_cabinetsmanager'),
        ('users', '0002_alter_users_enterprise_id_alter_users_personal_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CabinetsManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_datetime', models.DateTimeField(auto_now_add=True)),
                ('final_datetime', models.DateTimeField(blank=True)),
                ('cabinet_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cabinets.cabinets')),
                ('owner', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='users.users')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeExit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authorized', models.BooleanField(default=False)),
                ('cabinet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cabinets.cabinets')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.users')),
            ],
        ),
    ]
