# Generated by Django 5.1.7 on 2025-04-02 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinets_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabinetsmanager',
            name='final_datetime',
            field=models.DateTimeField(null=True),
        ),
    ]
