# Generated by Django 5.1.7 on 2025-04-02 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinets_manager', '0002_alter_cabinetsmanager_final_datetime'),
        ('users', '0002_alter_users_enterprise_id_alter_users_personal_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabinetsmanager',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.users'),
        ),
    ]
