# Generated by Django 5.1.7 on 2025-04-02 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinets', '0009_delete_cabinetsmanager'),
        ('cabinets_manager', '0003_alter_cabinetsmanager_owner'),
        ('users', '0002_alter_users_enterprise_id_alter_users_personal_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CabinetsManagerHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_datetime', models.DateTimeField()),
                ('final_datetime', models.DateTimeField()),
                ('cabinet_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cabinets.cabinets')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.users')),
            ],
        ),
    ]
