# Generated by Django 5.1.7 on 2025-04-02 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinets', '0009_delete_cabinetsmanager'),
        ('cabinets_manager', '0004_cabinetsmanagerhistory'),
        ('users', '0002_alter_users_enterprise_id_alter_users_personal_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabinetsmanagerhistory',
            name='cabinet_id',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='cabinets.cabinets'),
        ),
        migrations.AlterField(
            model_name='cabinetsmanagerhistory',
            name='final_datetime',
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='cabinetsmanagerhistory',
            name='initial_datetime',
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='cabinetsmanagerhistory',
            name='owner',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='users.users'),
        ),
    ]
