# Generated by Django 5.1.7 on 2025-04-02 22:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinets', '0009_delete_cabinetsmanager'),
        ('cabinets_manager', '0006_employeeexithistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabinetsmanagerhistory',
            name='cabinet_id',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='cabinets.cabinets'),
        ),
    ]
