# Generated by Django 5.1.7 on 2025-04-02 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinets_manager', '0007_alter_cabinetsmanagerhistory_cabinet_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeexithistory',
            name='authorized',
            field=models.BooleanField(editable=False),
        ),
    ]
