# Generated by Django 5.1.7 on 2025-04-04 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinets', '0009_delete_cabinetsmanager'),
        ('cabinets_manager', '0009_alter_employeeexithistory_cabinet'),
        ('users', '0002_alter_users_enterprise_id_alter_users_personal_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authorized', models.BooleanField(editable=False)),
                ('initial_datetime', models.DateTimeField(editable=False)),
                ('final_datetime', models.DateTimeField(editable=False)),
                ('cabinet', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='cabinets.cabinets')),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='users.users')),
            ],
        ),
    ]
